¿Qué es la Función ReLU?
ReLU (Rectified Linear Unit) es una de las funciones de activación más utilizadas en redes neuronales profundas. Su simplicidad y eficiencia la han convertido en una elección popular para muchas arquitecturas. Básicamente, la función ReLU devuelve el valor de entrada si este es positivo, y cero en caso contrario.

In [10]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

x = np.array([-1, 2, -3, 4])
y = relu(x)
print(y)  # Output: [0 2 0 4]

[0 2 0 4]


In [11]:
import numpy as np

# Crear un tensor (arreglo multidimensional)
tensor = np.array([[1, 2, 3], [4, 5, 6]])
print(tensor)

[[1 2 3]
 [4 5 6]]


Creación de un modelo de red neuronal simple con Scikit-learn:

In [12]:
from sklearn.neural_network import MLPClassifier

# Crear un clasificador de perceptrón multicapa
clf = MLPClassifier(hidden_layer_sizes=(10,), activation='relu', solver='adam', max_iter=1000)
# Suponiendo que X es la matriz de características y y es el vector de etiquetas
clf.fit(X, y)
# Hacer predicciones sobre nuevos datos
predicciones = clf.predict(nuevos_datos)

NameError: name 'X' is not defined

In [17]:
import tensor as tf


# Crear un modelo secuencial
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])


ModuleNotFoundError: No module named 'tensor'