# explicacion_numerica_de_MLP

Por:

Andrés Felipe Escallón Portilla
(4 y 9 - sep - 2024)

Referencias:

*Basic numerical examples (MLP and others):

https://www.linkedin.com/posts/tom-yeh_deeplearning-llms-generativeai-activity-7161408843111956480-ujq0/


- Perceptron:

https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-activity-7171891528448008192-nulK/?utm_source=share&utm_medium=member_android

- Video about MLP numerical operation:

https://www.linkedin.com/posts/annarahn_deeplearning-neuralnetworks-math-ugcPost-7171662948967411712-ZIEx?utm_source=share&utm_medium=member_android


*Other:

- https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-ugcPost-7174203548736319488-RM0S?utm_source=share&utm_medium=member_android


- https://alfanotv.com/raspberry-pi/como-multiplicar-matrices-en-numpy-multiply-matmul/



In [5]:
import numpy as np

array_1 = np.array(     [ [1, 1], [-1,1] ]   )


W = np.array(     [ [1, 1], [-1,1] ]   )
print("\n W = \n", W)
#print()


array_2 = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )

X = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )
print("\n X = \n",X)
#print()

WX_1 = np.dot(W,X)
print("\n WX_1 = \n",WX_1)
#print()

WX_2 = np.matmul(W,X)
print("\n WX_2 = \n",WX_2)
#print()

#XW = np.matmul(X,W)
#print(XW)
#print()
# Lo anterior no funciona por lo siguiente:
#X_(2,3) por W_(2,2) = Resultado_(2,2)?
#porque el numero de columnas de X es diferente al numero de filas de W


 W = 
 [[ 1  1]
 [-1  1]]

 X = 
 [[1 5 2]
 [2 4 2]]

 WX_1 = 
 [[ 3  9  4]
 [ 1 -1  0]]

 WX_2 = 
 [[ 3  9  4]
 [ 1 -1  0]]



```
W_(2,2) por X_(2,3) = WX_(2,3)

W*x + b = Z ---> Activation = output

W_(3,4) por x_(4,5) = Z_(3,5)

Asumiendo que todos los biases son cero y que NO hay función de activación (es decir: se deja pasar la misma información)

```


w.x+b

In [6]:
W = np.array([   [1,1,0,-1], [-1,1,2,-3], [-1,1,5,0]  ])
print(W)

print()

x = np.array([ [1,5,2,-1,0], [2,4,2,1,-1], [7,5,6,-1,1], [-8,0,4,-1,3] ])
print(x)
print()

b = np.zeros((3, 5)) # suponer todos los valores de los biases en cero
print(b)
print()

Z = np.matmul(W,x) + b
print(Z)

[[ 1  1  0 -1]
 [-1  1  2 -3]
 [-1  1  5  0]]

[[ 1  5  2 -1  0]
 [ 2  4  2  1 -1]
 [ 7  5  6 -1  1]
 [-8  0  4 -1  3]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[11.  9.  0.  1. -4.]
 [39.  9.  0.  3. -8.]
 [36. 24. 30. -3.  4.]]


# Explicación manual:

```
W =
[[ 1  1]
 [-1  1]]

x=
 [[1 5 2]
 [2 4 2]]

Entonces:

W*x + b:

b=zeros
W*x  + 0 = W*x = Z
[[ 3  9  4]
 [ 1 -1  0]]

Z-->relu-->A
A=
[[ 3  9  4]
 [ 1  0  0]]

===============
W*x =
[[ 3  9  4]
 [ 1 -1  0]]

+ b (b=ones)
W*x + b:
[[ 4  10  5]
 [ 2  0   1]]

W*x + b = Z
Z-->relu-->A

A=
[[ 4  10  5]
 [ 2  0   0]]

=========================

Comparar el resultado conocido (Supervisado)
Supongamos que el resultado conocido es:
Y_real=
[[ 4  10  5]
 [ 2  0   0]]
y sucedió que la red calculó y dio:
A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ 0  0  0]
 [ 0  0   0]]

===============================================
O supongamos que el resultado conocido debe ser:
Y_real=
[[ -3  6  2]
 [ 0   5 -1]]
y sucedió que la red calculó y dio:

A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ -7  -4  -3]
 [ -2  5   -1]]


```






In [7]:
import numpy as np

Y_real = np.array([[-3,6,2],[0,5,-1]])
print(Y_real)
print()
Y_estimada = np.array([[4,10,5],[2,0,0]])
print(Y_estimada)
print()

Error1 = Y_real-Y_estimada
print(Error1)
print()
Error2 = Y_estimada - Y_real
print(Error2)

[[-3  6  2]
 [ 0  5 -1]]

[[ 4 10  5]
 [ 2  0  0]]

[[-7 -4 -3]
 [-2  5 -1]]

[[ 7  4  3]
 [ 2 -5  1]]


# Operaciones correctas vs incorrectas:

## Si no se cumple lo dicho incialmente, entonces no se puede multiplicar matrices desde el procedimiento de algebra lineal:

## "*" y multiply son para multiplicar elemento a elemento matrices del mismo tamaño = num_filas x num_columnas

In [8]:
#array_r_bad1 = array_1 * array_2
#print(array_r_bad1)

np.array([1,1])*np.array([1,1,1])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
print(np.array([2,4])*np.array([3,-5]))

In [ ]:
np.multiply(np.array([2,4]), np.array([3,-5]))

In [ ]:
array_r_bad2 = array_2 * array_1
print(array_r_bad2)

In [ ]:
mult3 = np.multiply(array_1,array_2)
print(mult3)

# HOMEWORK:

# Ejemplo académico:

Definiendo funciones en python para calcular:

 W x + b = Z --> relu ---> y

In [ ]:
def get_output_from_MLP_input(W,x,b,activation="linear"):
  #print("W = ",end='\n')
  #print(W)
  print(f"W = \n {W} \n")
  #print()

  print("x = ",end='\n')
  print(x)
  print("b = ",end='\n')
  print(b)
  # arguments:
  # W,x and b are arrays

  # operations
  # Z = W x  +  b
  #Z = np.matmul(W,x) + b
  Z = np.dot(W,x) + b

  print("Z = ",end='\n')
  print(Z)

  if activation=="linear":
    y = Z

  if activation=="relu":
    # Ternary operator to define a relu function
    #y = Z if Z>=0 else 0
    #y = Z if Z>0 else 0
    #y = 0 if Z<0 else Z
    #y = 0 if Z<=0 else Z
    y = np.array([0 if z<=0 else z for z in Z])

  #TO-DO:
  """
  if activation=="sigmoid":
    #
  if activation=="tanh":
    #
  # Use many others
  if activation=="":
    #
  if activation=="":
    #
  ...

  """

  print("y = ",end='\n')
  print(y)

  return y

In [ ]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b)
y

In [ ]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b, activation="linear")
y

In [ ]:
# Testing (relu)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"relu")
y

# Ojo: la multiplicacion entre matrices en general NO es conmutativa

AB=C en general es distinto de BA=D

(suponiendo que por las dimensiones se puedan operar)

Ejemplo: al intercambiar Wx con xW hay error

In [ ]:
y = get_output_from_MLP_input(x,W,b)